import streamlit as st
import streamlit.components.v1 as components

# 1. Setup page layout
st.set_page_config(
    page_title="NES Emulator Hub",
    layout="centered",
    initial_sidebar_state="collapsed"
)

st.title("🕹️ Retro NES Emulator")
st.caption("Built with Streamlit & EmulatorJS. Run your favorite retro tests directly in the browser.")

# 2. Immutably structured HTML array to prevent any mobile indentation errors
html_lines = [
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">',
    "    <style>",
    "        body { background-color: #0e1117; color: #ffffff; font-family: system-ui, sans-serif; margin: 0; padding: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; }",
    "        #picker-container { text-align: center; padding: 40px 20px; border: 2px dashed #31333f; border-radius: 10px; background: #131722; width: 80%; max-width: 500px; }",
    "        .btn-upload { display: inline-block; background-color: #ff4b4b; color: white; padding: 12px 24px; border-radius: 8px; font-weight: 600; cursor: pointer; margin-top: 15px; }",
    '        input[type="file"] { display: none; }',
    "        #game-container { display: none; width: 100%; height: 650px; }",
    "        #game { width: 100%; height: 100%; }",
    "",
    "        /* LANDSCAPE BREAKOUT FIX */",
    "        @media (min-width: 500px) {",
    "            #game-container { height: 380px !important; }",
    "",
    "            /* Use position: fixed to break free from the centered parent box completely */",
    "            .ejs-sidebar-move {",
    "                position: fixed !important;",
    "                bottom: 20px !important;",
    "                z-index: 999999 !important;",
    "                background: rgba(255, 255, 255, 0.12) !important;",
    "                border: 1px solid rgba(255, 255, 255, 0.25) !important;",
    "                border-radius: 6px !important;",
    "                padding: 6px 12px !important;",
    "                font-size: 13px !important;",
    "                font-weight: bold !important;",
    "                letter-spacing: 0.5px !important;",
    "            }",
    "",
    "            /* Send Select & Start to the far left under the D-Pad */",
    '            [data-control="select"] { left: 20px !important; right: auto !important; }',
    '            [data-control="start"] { left: 105px !important; right: auto !important; }',
    "",
    "            /* Send Fast & Slow to the far right under the B/A buttons */",
    '            [data-control="fast"] { right: 105px !important; left: auto !important; }',
    '            [data-control="slow"] { right: 20px !important; left: auto !important; }',
    "        }",
    "    </style>",
    "</head>",
    "<body>",
    "",
    '    <div id="picker-container">',
    "        <h3>Load your NES Game</h3>",
    '        <p style="color: #a3a8b4; font-size: 14px;">Select a .nes or .zip ROM file from your phone storage to start playing.</p>',
    '        <label class="btn-upload">Choose File<input type="file" id="rom-file" accept=".nes,.zip"></label>',
    "    </div>",
    "",
    '    <div id="game-container"><div id="game"></div></div>',
    "",
    '    <script type="text/javascript">',
    "        document.getElementById('rom-file').addEventListener('change', function(e) {",
    "            const file = e.target.files[0];",
    "            if (!file) return;",
    "            ",
    "            window.EJS_player = '#game';",
    "            window.EJS_core = 'nes';",
    "            window.EJS_pathtodata = 'https://cdn.emulatorjs.org/stable/data/';",
    "            window.EJS_gameUrl = URL.createObjectURL(file);",
    "            ",
    "            document.getElementById('picker-container').style.display = 'none';",
    "            document.getElementById('game-container').style.display = 'block';",
    "            ",
    "            const loaderScript = document.createElement('script');",
    "            loaderScript.src = 'https://cdn.emulatorjs.org/stable/data/loader.js';",
    "            document.body.appendChild(loaderScript);",
    "",
    "            // Actively sweep the DOM to capture, label, and isolate the targeted buttons",
    "            setInterval(() => {",
    "                const gameDiv = document.getElementById('game');",
    "                if (!gameDiv) return;",
    "                const elements = gameDiv.getElementsByTagName('*');",
    "                for (let el of elements) {",
    "                    if (el.children.length === 0) {",
    "                        const txt = el.textContent.trim();",
    "                        if (['Start', 'Select', 'Fast', 'Slow'].includes(txt)) {",
    "                            el.classList.add('ejs-sidebar-move');",
    "                            el.setAttribute('data-control', txt.toLowerCase());",
    "                            ",
    "                            // Wipe out the styles of the native central box container",
    "                            if (el.parentNode) {",
    "                                el.parentNode.style.border = 'none';",
    "                                el.parentNode.style.background = 'none';",
    "                                el.parentNode.style.boxShadow = 'none';",
    "                            }",
    "                        }",
    "                    }",
    "                }",
    "            }, 400);",
    "        });",
    "    </script>",
    "</body>",
    "</html>"
]

# 3. Compile and launch within Streamlit
emulator_html = "\n".join(html_lines)
components.html(emulator_html, height=720, scrolling=False)

st.info("💡 Note: Game files are processed locally on your device and are never uploaded to any server.")
