import streamlit as st
import streamlit.components.v1 as components

# 1. Setup page layout
st.set_page_config(
    page_title="NES Emulator Hub",
    layout="centered",
    initial_sidebar_state="collapsed"
)

st.title("🕹️ Retro NES Emulator")
st.caption("Built with Streamlit & EmulatorJS. Optimized for physical controller gameplay.")

# 2. HTML Structure with Widescreen Canvas Stretching & Fullscreen Utility
html_lines = [
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">',
    "    <style>",
    "        body { background-color: #0e1117; color: #ffffff; font-family: system-ui, sans-serif; margin: 0; padding: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; }",
    "        #picker-container { text-align: center; padding: 40px 20px; border: 2px dashed #31333f; border-radius: 10px; background: #131722; width: 80%; max-width: 500px; }",
    "        .btn-upload { display: inline-block; background-color: #ff4b4b; color: white; padding: 12px 24px; border-radius: 8px; font-weight: 600; cursor: pointer; margin-top: 15px; }",
    '        input[type="file"] { display: none; }',
    "        #game-container { display: none; width: 100%; height: 600px; position: relative; }",
    "        #game { width: 100%; height: 100%; }",
    "",
    "        /* LANDSCAPE WIDESCREEN AUTO-STRETCH */",
    "        @media (min-width: 500px) {",
    "            #game-container { height: 95vh !important; }",
    "            ",
    "            /* Force the native emulator video core to expand across all edges */",
    "            #game canvas {",
    "                width: 100% !important;",
    "                height: 100% !important;",
    "                object-fit: fill !important; /* Strips away all black pillarboxes and borders */",
    "            }",
    "            ",
    "            /* Dissolve old on-screen container frames to clean the landscape window */",
    "            div[style*='position: absolute'] {",
    "                background: none !important;",
    "                border: none !important;",
    "                box-shadow: none !important;",
    "            }",
    "        }",
    "        ",
    "        /* Floating Maximize Control */",
    "        #fs-btn {",
    "            display: none;",
    "            position: fixed;",
    "            top: 12px;",
    "            left: 12px;",
    "            z-index: 9999999;",
    "            background: #007aff;",
    "            color: white;",
    "            border: none;",
    "            padding: 10px 18px;",
    "            border-radius: 20px;",
    "            font-weight: 600;",
    "            cursor: pointer;",
    "            font-size: 13px;",
    "            box-shadow: 0 4px 12px rgba(0,0,0,0.4);",
    "        }",
    "    </style>",
    "</head>",
    "<body>",
    "",
    '    <button id="fs-btn" onclick="goFullScreen()">Maximize Widescreen</button>',
    "",
    '    <div id="picker-container">',
    "        <h3>Load your NES Game</h3>",
    '        <p style="color: #a3a8b4; font-size: 14px;">Select a .nes or .zip ROM file from your phone storage to start playing.</p>',
    '        <label class="btn-upload">Choose File<input type="file" id="rom-file" accept=".nes,.zip"></label>',
    "    </div>",
    "",
    '    <div id="game-container"><div id="game"></div></div>',
    "",
    '    <script type="text/javascript">',
    "        function goFullScreen() {",
    "            const el = document.documentElement;",
    "            if (!document.fullscreenElement) {",
    "                el.requestFullscreen().catch(err => {});",
    "                document.getElementById('fs-btn').innerText = 'Exit Maximize';",
    "            } else {",
    "                document.exitFullscreen();",
    "                document.getElementById('fs-btn').innerText = 'Maximize Widescreen';",
    "            }",
    "        }",
    "",
    "        document.getElementById('rom-file').addEventListener('change', function(e) {",
    "            const file = e.target.files[0];",
    "            if (!file) return;",
    "            ",
    "            window.EJS_player = '#game';",
    "            window.EJS_core = 'nes';", 
    "            window.EJS_pathtodata = 'https://cdn.emulatorjs.org/stable/data/';",
    "            window.EJS_gameUrl = URL.createObjectURL(file);",
    "            ",
    "            document.getElementById('picker-container').style.display = 'none';",
    "            document.getElementById('game-container').style.display = 'block';",
    "            document.getElementById('fs-btn').style.display = 'block';",
    "            ",
    "            const loaderScript = document.createElement('script');",
    "            loaderScript.src = 'https://cdn.emulatorjs.org/stable/data/loader.js';",
    "            document.body.appendChild(loaderScript);",
    "            ",
    "            // Background interval sweeps to hide the leftover utility text labels",
    "            setInterval(() => {",
    "                const gameDiv = document.getElementById('game');",
    "                if (!gameDiv) return;",
    "                const elements = gameDiv.getElementsByTagName('*');",
    "                for (let el of elements) {",
    "                    const txt = (el.textContent || el.innerText || '').trim();",
    "                    if (['Start', 'Select', 'Fast', 'Slow'].includes(txt)) {",
    "                        el.style.display = 'none'; ",
    "                    }",
    "                }",
    "            }, 400);",
    "        });",
    "    </script>",
    "</body>",
    "</html>"
]

# 3. Assemble and deploy inside Streamlit
emulator_html = "\n".join(html_lines)
components.html(emulator_html, height=720, scrolling=False)

st.info("💡 Note: Game files are processed locally on your device and are never uploaded to any server.")
